// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJ6xV9LxCVRAMebl-74ZF_K7q64ErM_c',
    appId: '1:267064172996:web:9257457123322e7d830491',
    messagingSenderId: '267064172996',
    projectId: 'peachy-5318e',
    authDomain: 'peachy-5318e.firebaseapp.com',
    storageBucket: 'peachy-5318e.appspot.com',
    measurementId: 'G-FW28RFFDZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDKIxY25BLEpTwz_HVsJstA_fnK-WqM0U',
    appId: '1:267064172996:android:f43d3a14b4a0958e830491',
    messagingSenderId: '267064172996',
    projectId: 'peachy-5318e',
    storageBucket: 'peachy-5318e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBeAmJWAANCKLSr3TNMjLbsUHa9ROyYVw',
    appId: '1:267064172996:ios:dea4fc914b008594830491',
    messagingSenderId: '267064172996',
    projectId: 'peachy-5318e',
    storageBucket: 'peachy-5318e.appspot.com',
    iosBundleId: 'com.example.peachy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBeAmJWAANCKLSr3TNMjLbsUHa9ROyYVw',
    appId: '1:267064172996:ios:dea4fc914b008594830491',
    messagingSenderId: '267064172996',
    projectId: 'peachy-5318e',
    storageBucket: 'peachy-5318e.appspot.com',
    iosBundleId: 'com.example.peachy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdJ6xV9LxCVRAMebl-74ZF_K7q64ErM_c',
    appId: '1:267064172996:web:a2a5b6d2bea754bc830491',
    messagingSenderId: '267064172996',
    projectId: 'peachy-5318e',
    authDomain: 'peachy-5318e.firebaseapp.com',
    storageBucket: 'peachy-5318e.appspot.com',
    measurementId: 'G-K954EQHQZF',
  );

}